import { FhevmType } from "@fhevm/hardhat-plugin";
import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";
import fs from "node:fs";
import path from "node:path";

task("vault:addresses", "Print CipherVault and ConfidentialUSDT addresses").setAction(async function (
  _taskArguments: TaskArguments,
  hre,
) {
  const { deployments } = hre;
  const vault = await deployments.get("CipherVault");
  const cusdt = await deployments.get("ConfidentialUSDT");
  console.log(`CipherVault      : ${vault.address}`);
  console.log(`ConfidentialUSDT : ${cusdt.address}`);
});

task("vault:export-frontend", "Write home/src/config/contracts.ts from deployments")
  .addOptionalParam("out", "Output path (defaults to home/src/config/contracts.ts)")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { deployments, network } = hre;

    const vault = await deployments.get("CipherVault");
    const cusdt = await deployments.get("ConfidentialUSDT");

    const outPath = path.resolve(process.cwd(), taskArguments.out ?? "home/src/config/contracts.ts");

    const contents = `/* Auto-generated by hardhat task vault:export-frontend (network=${network.name}). */\n` +
      `\n` +
      `export const WEI_PER_MICRO_ETH = 1_000_000_000_000;\n` +
      `\n` +
      `export const CIPHER_VAULT_ADDRESS = '${vault.address}' as const;\n` +
      `export const CONFIDENTIAL_USDT_ADDRESS = '${cusdt.address}' as const;\n` +
      `\n` +
      `export const CIPHER_VAULT_ABI = ${JSON.stringify(vault.abi, null, 2)} as const;\n` +
      `\n` +
      `export const CONFIDENTIAL_USDT_ABI = ${JSON.stringify(cusdt.abi, null, 2)} as const;\n`;

    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, contents, "utf8");

    console.log(`Wrote ${outPath}`);
  });

task("vault:stake", "Stake ETH into CipherVault")
  .addParam("eth", "ETH amount (e.g. 0.01)")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { ethers, deployments } = hre;

    const vault = await deployments.get("CipherVault");
    const [signer] = await ethers.getSigners();
    const contract = await ethers.getContractAt("CipherVault", vault.address, signer);

    const value = ethers.parseEther(taskArguments.eth);
    const tx = await contract.stake({ value });
    console.log(`Wait for tx:${tx.hash}...`);
    const receipt = await tx.wait();
    console.log(`tx:${tx.hash} status=${receipt?.status}`);
  });

task("vault:borrow", "Borrow encrypted cUSDT from CipherVault")
  .addParam("amount", "cUSDT amount in micro units (6 decimals), e.g. 123456 = 0.123456")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { ethers, deployments, fhevm } = hre;

    await fhevm.initializeCLIApi();

    const amount = BigInt(taskArguments.amount);
    const vault = await deployments.get("CipherVault");
    const [signer] = await ethers.getSigners();

    const encryptedInput = await fhevm.createEncryptedInput(vault.address, signer.address).add64(amount).encrypt();

    const contract = await ethers.getContractAt("CipherVault", vault.address, signer);
    const tx = await contract.borrow(encryptedInput.handles[0], encryptedInput.inputProof);
    console.log(`Wait for tx:${tx.hash}...`);
    const receipt = await tx.wait();
    console.log(`tx:${tx.hash} status=${receipt?.status}`);
  });

task("vault:repay", "Repay cUSDT using ConfidentialUSDT confidentialTransferAndCall")
  .addParam("amount", "cUSDT amount in micro units (6 decimals)")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { ethers, deployments, fhevm } = hre;

    await fhevm.initializeCLIApi();

    const amount = BigInt(taskArguments.amount);
    const vault = await deployments.get("CipherVault");
    const cusdt = await deployments.get("ConfidentialUSDT");

    const [signer] = await ethers.getSigners();
    const token = await ethers.getContractAt("ConfidentialUSDT", cusdt.address, signer);

    const encryptedInput = await fhevm.createEncryptedInput(cusdt.address, signer.address).add64(amount).encrypt();

    const tx = await token["confidentialTransferAndCall(address,bytes32,bytes,bytes)"](
      vault.address,
      encryptedInput.handles[0],
      encryptedInput.inputProof,
      "0x",
    );
    console.log(`Wait for tx:${tx.hash}...`);
    const receipt = await tx.wait();
    console.log(`tx:${tx.hash} status=${receipt?.status}`);
  });

task("vault:decrypt", "Decrypt user vault collateral/debt and cUSDT balance")
  .addOptionalParam("user", "User address (defaults to signer[0])")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { ethers, deployments, fhevm } = hre;

    await fhevm.initializeCLIApi();

    const vault = await deployments.get("CipherVault");
    const cusdt = await deployments.get("ConfidentialUSDT");

    const signers = await ethers.getSigners();
    const signer = signers[0];
    const user = taskArguments.user ?? signer.address;

    const vaultContract = await ethers.getContractAt("CipherVault", vault.address, signer);
    const token = await ethers.getContractAt("ConfidentialUSDT", cusdt.address, signer);

    const encryptedCollateral = await vaultContract.collateralMicroEthOf(user);
    const encryptedDebt = await vaultContract.debtMicroUsdtOf(user);
    const encryptedBalance = await token.confidentialBalanceOf(user);

    console.log(`CipherVault      : ${vault.address}`);
    console.log(`ConfidentialUSDT : ${cusdt.address}`);
    console.log(`User             : ${user}`);

    const collateral = encryptedCollateral === ethers.ZeroHash
      ? 0n
      : await fhevm.userDecryptEuint(FhevmType.euint64, encryptedCollateral, vault.address, signer);
    const debt = encryptedDebt === ethers.ZeroHash ? 0n : await fhevm.userDecryptEuint(FhevmType.euint64, encryptedDebt, vault.address, signer);
    const balance = encryptedBalance === ethers.ZeroHash
      ? 0n
      : await fhevm.userDecryptEuint(FhevmType.euint64, encryptedBalance, cusdt.address, signer);

    console.log(`Collateral (microETH): ${collateral}`);
    console.log(`Debt (microUSDT)     : ${debt}`);
    console.log(`cUSDT balance        : ${balance}`);
  });
